### PR TITLE
Make public members of Analytics class virtual 

### PR DESCRIPTION
**Pull request by jn011**
Hi there!

I've recently started migrating to this library for integration and had noticed that it does not expose an interface which can be easily used to interact with the class.

I have created one called `IAnalytics` in this PR. This could potentially be used for dependency injection and also has the benefit of making it more testable.

Please let me know if you have any questions or thoughts.

Thanks!

### CODE REVIEW

**Comment by jn011** [comment]
Hi @wenxi-zeng 

Thanks for the background info, that makes sense.

Although it doesn't solve my use case since some concrete methods like track and identify are not marked as virtual which means they can't be easily unit tested.

My next thought Is could we make these Methods virtual? 

This would be similar to what we have for Flush at the moment.

**Comment by wenxi-zeng** [comment]
@jn011 yeah. making the methods all virtual is a good suggestion. would you mind to update the pr with that change? happy to marge that in! thanks!

**Comment by jn011** [comment]
@wenxi-zeng sounds good. I've just updated my branch

**Comment by wenxi-zeng** [comment]
@jn011 thanks for your contribution! this change will be released along with the feature request of adding support for sync flush

**Pull request merged**
